### ISSUE TITLE
Text editor seems wonky on profiles

### ISSUE THREAD

**Issue by philipjohn** [Automattic/govpack#44]
Found this on my vanilla test install. When I went to create a new Profile, the text editor was selected and all the formatting icons were wide and laid out one after another like so:

![Screenshot from 2021-05-14 16-06-45](https://user-images.githubusercontent.com/136342/118290621-8bffec80-b4ce-11eb-9d72-25dd2a471786.png)

**Comment by paulschreiber** [comment]
The `.cmb2-postbox .cmb-row.cmb-type-wysiwyg input` selector is causing the problem.
